In [ ]:
#import necessary libraries
import pandas as pd
import numpy as np
from random import sample

In [ ]:
# setting the variables for number of simulations, and respective weight of each parameter for the "match simulator" function

N = 5000
player_weight = 0.60
h2h_weight = 0.05
random_weight = 0.35
std = 10

In [ ]:
# Grabbing the data obtained through web scraping and the FIFA api

fifa = pd.read_csv("players_20.csv")
confederations = pd.read_csv("organizations.csv")
games = pd.read_csv("game_matrix.csv")

In [ ]:
# Serbia was missing from the orgs dataset
serb = {"Organization":"UEFA", "Country": "Serbia"}
confederations = confederations.append(serb, ignore_index=True)

In [ ]:
# Filtering the countries with more than 15 players

viable_countries= fifa["nationality"].value_counts()
viable_countries = viable_countries[viable_countries < 15]
viable_countries= viable_countries.index
viable_countries= list(viable_countries)

In [ ]:
fifa = fifa[~fifa['nationality'].isin(viable_countries)]

In [ ]:
# Grouping the best 20 players per country (15-20 if they don't have 20 players) and finding the squad strenght

team_averages = fifa.groupby("nationality")["overall"].nlargest(20).mean(level=0).reset_index(name="overall")

In [ ]:
team_averages = team_averages.merge(confederations, how='left', left_on='nationality', right_on='Country')

In [ ]:
team_averages.drop("nationality", axis=1, inplace= True)

In [ ]:
organization_df = {"Organization":["CONMEBOL", "AFC","CONCACAF","OFC","CAF","UEFA"],"Spots":[4,4,3,0,5,13]}

In [ ]:
organization_df = pd.DataFrame(organization_df)

In [ ]:
games.columns = games.columns.str.lstrip()
games.columns = games.columns.str.rstrip()

In [ ]:
games["Country"]= games["Country"].str.lstrip()
games["Country"]= games["Country"].str.rstrip()

In [ ]:
games=games.merge(team_averages, how="left", on="Country")

In [ ]:
games

           Country Spain Brazil France  ... Canada Qatar overall Organization
0            Spain     0    0.4   0.57  ...      1   NA    85.90         UEFA
1           Brazil   0.6      0    0.5  ...      1     1   85.85     CONMEBOL
2           France  0.43    0.5      0  ...      1   NA    85.65         UEFA
3          Germany  0.56   0.28   0.42  ...      1   NA    85.25         UEFA
4            Italy  0.43   0.36   0.62  ...      1   NA    83.75         UEFA
5        Argentina   0.5   0.47   0.67  ...      1     1   83.80     CONMEBOL
6         Portugal  0.25   0.25   0.25  ...      1   NA    83.55         UEFA
7          Belgium  0.29    0.4   0.55  ...      1     1   83.75         UEFA
8          England  0.58   0.27   0.68  ...    NA    NA    82.60         UEFA
9      Netherlands   0.6    0.5   0.44  ...      1   NA    82.35         UEFA
10         Uruguay     0   0.22    0.4  ...      1   NA    81.95     CONMEBOL
11         Croatia  0.43      0      0  ...    NA      1   80.80         UEFA
12        Colombia     0   0.14   0.25  ...   0.75     1   79.50     CONMEBOL
13     Switzerland  0.06    0.4   0.43  ...      0     0   78.85         UEFA
14         Denmark  0.14   0.33   0.33  ...      1     1   78.55         UEFA
15          Mexico     0   0.29   0.17  ...   0.88   NA    78.20     CONCACAF
16         Senegal   NA     NA       1  ...    NA    NA    78.05          CAF
17   Cote d'Ivoire     0      0      0  ...    NA      1   77.85          CAF
18          Turkey  0.25      0   0.17  ...      1     1   77.25         UEFA
19          Poland  0.11   0.11   0.27  ...      1   NA    78.35         UEFA
20           Chile  0.11   0.14    0.5  ...   0.67   NA    77.65     CONMEBOL
21         Morocco     0      0      0  ...   0.67     1   77.45          CAF
22         Algeria     0      0   0.75  ...      1  0.33   76.70          CAF
23         Nigeria   0.5      0    0.5  ...      0   NA    75.70          CAF
24           Japan     0      0    0.2  ...      1   0.5   75.60          AFC
25             USA   0.2   0.05      0  ...   0.63   NA    75.25     CONCACAF
26  Korea Republic   0.2   0.17      0  ...    0.5  0.56   73.65          AFC
27       Australia     0   0.14   0.25  ...   0.63  0.75   72.95          AFC
28        China PR     0      0    0.5  ...   0.67  0.54   70.95          AFC
29    Saudi Arabia     0      0      0  ...      1  0.72   70.30          AFC
30          Canada     0      0      0  ...      0   NA    70.55     CONCACAF
31           Qatar   NA       0    NA   ...    NA      0     NaN          NaN

[32 rows x 35 columns]

In [ ]:
games.set_index('Country',drop=False, inplace=True)

In [ ]:
qualified_teams= pd.DataFrame(games)

In [ ]:
qatgames= {"overall":60, "Organization": "AFC"}
qualified_teams.fillna(value=qatgames, axis=0, limit=1, inplace=True)

In [ ]:
qualified_teams

                       Country Spain Brazil  ... Qatar overall Organization
Country                                      ...
Spain                    Spain     0    0.4  ...   NA    85.90         UEFA
Brazil                  Brazil   0.6      0  ...     1   85.85     CONMEBOL
France                  France  0.43    0.5  ...   NA    85.65         UEFA
Germany                Germany  0.56   0.28  ...   NA    85.25         UEFA
Italy                    Italy  0.43   0.36  ...   NA    83.75         UEFA
Argentina            Argentina   0.5   0.47  ...     1   83.80     CONMEBOL
Portugal              Portugal  0.25   0.25  ...   NA    83.55         UEFA
Belgium                Belgium  0.29    0.4  ...     1   83.75         UEFA
England                England  0.58   0.27  ...   NA    82.60         UEFA
Netherlands        Netherlands   0.6    0.5  ...   NA    82.35         UEFA
Uruguay                Uruguay     0   0.22  ...   NA    81.95     CONMEBOL
Croatia                Croatia  0.43      0  ...     1   80.80         UEFA
Colombia              Colombia     0   0.14  ...     1   79.50     CONMEBOL
Switzerland        Switzerland  0.06    0.4  ...     0   78.85         UEFA
Denmark                Denmark  0.14   0.33  ...     1   78.55         UEFA
Mexico                  Mexico     0   0.29  ...   NA    78.20     CONCACAF
Senegal                Senegal   NA     NA   ...   NA    78.05          CAF
Cote d'Ivoire    Cote d'Ivoire     0      0  ...     1   77.85          CAF
Turkey                  Turkey  0.25      0  ...     1   77.25         UEFA
Poland                  Poland  0.11   0.11  ...   NA    78.35         UEFA
Chile                    Chile  0.11   0.14  ...   NA    77.65     CONMEBOL
Morocco                Morocco     0      0  ...     1   77.45          CAF
Algeria                Algeria     0      0  ...  0.33   76.70          CAF
Nigeria                Nigeria   0.5      0  ...   NA    75.70          CAF
Japan                    Japan     0      0  ...   0.5   75.60          AFC
USA                        USA   0.2   0.05  ...   NA    75.25     CONCACAF
Korea Republic  Korea Republic   0.2   0.17  ...  0.56   73.65          AFC
Australia            Australia     0   0.14  ...  0.75   72.95          AFC
China PR              China PR     0      0  ...  0.54   70.95          AFC
Saudi Arabia      Saudi Arabia     0      0  ...  0.72   70.30          AFC
Canada                  Canada     0      0  ...   NA    70.55     CONCACAF
Qatar                    Qatar   NA       0  ...     0   60.00          AFC

[32 rows x 35 columns]

In [ ]:
games.replace(" NA ",0, inplace=True)
games.replace("#VALUE!",0, inplace=True)

In [ ]:
# "Match simulator" function used to determine the tournament outcome

def compare_teams(country1, country2): 
  country1_average = float(qualified_teams.loc[country1,"overall"])
  country2_average = float(qualified_teams.loc[country2,"overall"]) 
  country1_h2h = float(games.loc[country1,country2])
  country2_h2h = float(games.loc[country2,country1])

  if country1_h2h is None:
    country1_score = player_weight * country1_average + (1 - player_weight) * np.random.normal(1, 0, std)
    country2_score = player_weight * country2_average + (1 - player_weight) * np.random.normal(1, 0, std)
  else: 
    country1_score = player_weight * country1_average + country1_h2h * h2h_weight + country1_average + random_weight * np.random.normal(0, std, 1)
    country2_score = player_weight * country2_average + country2_h2h * h2h_weight + country2_average + random_weight * np.random.normal(0, std, 1)
  
  if country1_score > country2_score:
    return country1
  else:
    return country2

In [ ]:
# Setting up a counter dataframe that will count the times that each team makes it through the group stage

wins = {"Country": qualified_teams["Country"], "Wins": np.repeat(0,len(qualified_teams["Country"]))}
wins = pd.DataFrame(wins)

In [ ]:
# Setting up a counter dataframe that will count the times that each team wins the World Cup

whole_wins = {"Country": qualified_teams["Country"], "Wins": np.repeat(0,len(qualified_teams["Country"]))}
whole_wins = pd.DataFrame(whole_wins)
whole_wins

                       Country  Wins
Country
Spain                    Spain     0
Brazil                  Brazil     0
France                  France     0
Germany                Germany     0
Italy                    Italy     0
Argentina            Argentina     0
Portugal              Portugal     0
Belgium                Belgium     0
England                England     0
Netherlands        Netherlands     0
Uruguay                Uruguay     0
Croatia                Croatia     0
Colombia              Colombia     0
Switzerland        Switzerland     0
Denmark                Denmark     0
Mexico                  Mexico     0
Senegal                Senegal     0
Cote d'Ivoire    Cote d'Ivoire     0
Turkey                  Turkey     0
Poland                  Poland     0
Chile                    Chile     0
Morocco                Morocco     0
Algeria                Algeria     0
Nigeria                Nigeria     0
Japan                    Japan     0
USA                        USA     0
Korea Republic  Korea Republic     0
Australia            Australia     0
China PR              China PR     0
Saudi Arabia      Saudi Arabia     0
Canada                  Canada     0
Qatar                    Qatar     0

In [ ]:
wins.reset_index(drop=True, inplace=True)

In [ ]:
whole_wins.reset_index(drop=True, inplace=True)

In [ ]:
whole_wins

           Country  Wins
0            Spain     0
1           Brazil     0
2           France     0
3          Germany     0
4            Italy     0
5        Argentina     0
6         Portugal     0
7          Belgium     0
8          England     0
9      Netherlands     0
10         Uruguay     0
11         Croatia     0
12        Colombia     0
13     Switzerland     0
14         Denmark     0
15          Mexico     0
16         Senegal     0
17   Cote d'Ivoire     0
18          Turkey     0
19          Poland     0
20           Chile     0
21         Morocco     0
22         Algeria     0
23         Nigeria     0
24           Japan     0
25             USA     0
26  Korea Republic     0
27       Australia     0
28        China PR     0
29    Saudi Arabia     0
30          Canada     0
31           Qatar     0

In [ ]:
wins

           Country  Wins
0            Spain     0
1           Brazil     0
2           France     0
3          Germany     0
4            Italy     0
5        Argentina     0
6         Portugal     0
7          Belgium     0
8          England     0
9      Netherlands     0
10         Uruguay     0
11         Croatia     0
12        Colombia     0
13     Switzerland     0
14         Denmark     0
15          Mexico     0
16         Senegal     0
17   Cote d'Ivoire     0
18          Turkey     0
19          Poland     0
20           Chile     0
21         Morocco     0
22         Algeria     0
23         Nigeria     0
24           Japan     0
25             USA     0
26  Korea Republic     0
27       Australia     0
28        China PR     0
29    Saudi Arabia     0
30          Canada     0
31           Qatar     0

In [ ]:
# Simulating the tournament 5000 times

for i in range(0,N):
  print("Iteration", i, "of", N,".")
  new_final = qualified_teams.sample(frac=1)
  group1 = new_final.iloc[range(0,4)]
  group2 = new_final.iloc[range(4,8)]
  group3 = new_final.iloc[range(8,12)]
  group4 = new_final.iloc[range(12,16)]
  group5 = new_final.iloc[range(16,20)]
  group6 = new_final.iloc[range(20,24)]
  group7 = new_final.iloc[range(24,28)]
  group8 = new_final.iloc[range(28,32)] 
  groups = [group1,group2,group3,group4,group5,group6,group7,group8]
  group_winners= []
  for group in groups:
    random_teams = np.random.choice(range(0,4),2,replace=True)
    group["overall"].iloc[random_teams[0]] = group["overall"].iloc[random_teams[0]]+1
    group["overall"].iloc[random_teams[1]] = group["overall"].iloc[random_teams[1]]+1
    sorted_group = group.sort_values(by="overall", ascending=False)
    wins.loc[wins['Country']==sorted_group["Country"].iloc[0], 'Wins'] += 1
    wins.loc[wins['Country']==sorted_group["Country"].iloc[1], 'Wins'] += 1
    group_winners.append(sorted_group["Country"].iloc[0])
    group_winners.append(sorted_group["Country"].iloc[1])

  round1_winners = []
  a1 = group_winners[0] #A1
  b2 = group_winners[3] #B2
  w = compare_teams(a1, b2)
  round1_winners.append(w)

  a2 = group_winners[1] #A2
  b1 = group_winners[2] #B1
  w = compare_teams(a2, b1)
  round1_winners.append(w)

  c1 = group_winners[4] #C1
  d2 = group_winners[7] #D2
  w = compare_teams(c1, d2)
  round1_winners.append(w)
    
  c2 = group_winners[5] #C2
  d1 = group_winners[6] #D1
  w = compare_teams(c2, d1)
  round1_winners.append(w)

  e1 = group_winners[8] #E1
  f2 = group_winners[11] #F2
  w = compare_teams(e1, f2)
  round1_winners.append(w)

  e2 = group_winners[9] #E2
  f1 = group_winners[10] #F1
  w = compare_teams(e2, f1)
  round1_winners.append(w)

  g1 = group_winners[12] #G1
  h2 = group_winners[15] #H2
  w = compare_teams(g1, h2)
  round1_winners.append(w)

  g2 = group_winners[13] #G2
  h1 = group_winners[14] #H1
  w = compare_teams(g2, h1)
  round1_winners.append(w) 

  round2_winners = []

  a1b2 = round1_winners[0]
  c1d2 = round1_winners[2]
  w = compare_teams(a1b2, c1d2)
  round2_winners.append(w)

  a2b1 = round1_winners[1]
  c2d1 = round1_winners[3]
  w = compare_teams(a2b1, c2d1)
  round2_winners.append(w)

  e1f2 = round1_winners[4]
  g1h2 = round1_winners[6]
  w = compare_teams(e1f2, g1h2)
  round2_winners.append(w)

  e2f1 = round1_winners[5]
  g2h1 = round1_winners[7]
  w = compare_teams(e2f1, g2h1)
  round2_winners.append(w) 

  round3_winners = []
  c1 = round2_winners[0]
  c2 = round2_winners[2]
  w = compare_teams(c1, c2)
  round3_winners.append(w)
  
  c3 = round2_winners[1]
  c4 = round2_winners[3]
  w = compare_teams(c3, c4)
  round3_winners.append(w)

  c1 = round3_winners[0]
  c2 = round3_winners[1]
  wm = compare_teams(c1, c2)
  whole_wins.loc[whole_wins['Country']==wm, 'Wins'] += 1

Iteration 0 of 5000 .
Iteration 1 of 5000 .
Iteration 2 of 5000 .
Iteration 3 of 5000 .
Iteration 4 of 5000 .
Iteration 5 of 5000 .
Iteration 6 of 5000 .

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Iteration 7 of 5000 .
Iteration 8 of 5000 .
Iteration 9 of 5000 .
Iteration 10 of 5000 .
Iteration 11 of 5000 .
Iteration 12 of 5000 .
Iteration 13 of 5000 .
Iteration 14 of 5000 .
Iteration 15 of 5000 .
Iteration 16 of 5000 .
Iteration 17 of 5000 .
Iteration 18 of 5000 .
Iteration 19 of 5000 .
Iteration 20 of 5000 .
Iteration 21 of 5000 .
Iteration 22 of 5000 .
Iteration 23 of 5000 .
Iteration 24 of 5000 .
Iteration 25 of 5000 .
Iteration 26 of 5000 .
Iteration 27 of 5000 .
Iteration 28 of 5000 .
Iteration 29 of 5000 .
Iteration 30 of 5000 .
Iteration 31 of 5000 .
Iteration 32 of 5000 .
Iteration 33 of 5000 .
Iteration 34 of 5000 .
Iteration 35 of 5000 .
Iteration 36 of 5000 .
Iteration 37 of 5000 .
Iteration 38 of 5000 .
Iteration 39 of 5000 .
Iteration 40 of 5000 .
Iteration 41 of 5000 .
Iteration 42 of 5000 .
Iteration 43 of 5000 .
Iteration 44 of 5000 .
Iteration 45 of 5000 .
Iteration 46 of 5000 .
Iteration 47 of 5000 .
Iteration 48 of 5000 .
Iteration 49 of 5000 .
Iteration 50 of 5000 .
Iteration 51 of 5000 .
Iteration 52 of 5000 .
Iteration 53 of 5000 .
Iteration 54 of 5000 .
Iteration 55 of 5000 .
Iteration 56 of 5000 .
Iteration 57 of 5000 .
Iteration 58 of 5000 .
Iteration 59 of 5000 .
Iteration 60 of 5000 .
Iteration 61 of 5000 .
Iteration 62 of 5000 .
Iteration 63 of 5000 .
Iteration 64 of 5000 .
Iteration 65 of 5000 .
Iteration 66 of 5000 .
Iteration 67 of 5000 .
Iteration 68 of 5000 .
Iteration 69 of 5000 .
Iteration 70 of 5000 .
Iteration 71 of 5000 .
Iteration 72 of 5000 .
Iteration 73 of 5000 .
Iteration 74 of 5000 .
Iteration 75 of 5000 .
Iteration 76 of 5000 .
Iteration 77 of 5000 .
Iteration 78 of 5000 .
Iteration 79 of 5000 .
Iteration 80 of 5000 .
Iteration 81 of 5000 .
Iteration 82 of 5000 .
Iteration 83 of 5000 .
Iteration 84 of 5000 .
Iteration 85 of 5000 .
Iteration 86 of 5000 .
Iteration 87 of 5000 .
Iteration 88 of 5000 .
Iteration 89 of 5000 .
Iteration 90 of 5000 .
Iteration 91 of 5000 .
Iteration 92 of 5000 .
Iteration 93 of 5000 .
Iteration 94 of 5000 .
Iteration 95 of 5000 .
Iteration 96 of 5000 .
Iteration 97 of 5000 .
Iteration 98 of 5000 .
Iteration 99 of 5000 .
Iteration 100 of 5000 .
Iteration 101 of 5000 .
Iteration 102 of 5000 .
Iteration 103 of 5000 .
Iteration 104 of 5000 .
Iteration 105 of 5000 .
Iteration 106 of 5000 .
Iteration 107 of 5000 .
Iteration 108 of 5000 .
Iteration 109 of 5000 .
Iteration 110 of 5000 .
Iteration 111 of 5000 .
Iteration 112 of 5000 .
Iteration 113 of 5000 .
Iteration 114 of 5000 .
Iteration 115 of 5000 .
Iteration 116 of 5000 .
Iteration 117 of 5000 .
Iteration 118 of 5000 .
Iteration 119 of 5000 .
Iteration 120 of 5000 .
Iteration 121 of 5000 .
Iteration 122 of 5000 .
Iteration 123 of 5000 .
Iteration 124 of 5000 .
Iteration 125 of 5000 .
Iteration 126 of 5000 .
Iteration 127 of 5000 .
Iteration 128 of 5000 .
Iteration 129 of 5000 .
Iteration 130 of 5000 .
Iteration 131 of 5000 .
Iteration 132 of 5000 .
Iteration 133 of 5000 .
Iteration 134 of 5000 .
Iteration 135 of 5000 .
Iteration 136 of 5000 .
Iteration 137 of 5000 .
Iteration 138 of 5000 .
Iteration 139 of 5000 .
Iteration 140 of 5000 .
Iteration 141 of 5000 .
Iteration 142 of 5000 .
Iteration 143 of 5000 .
Iteration 144 of 5000 .
Iteration 145 of 5000 .
Iteration 146 of 5000 .
Iteration 147 of 5000 .
Iteration 148 of 5000 .
Iteration 149 of 5000 .
Iteration 150 of 5000 .
Iteration 151 of 5000 .
Iteration 152 of 5000 .
Iteration 153 of 5000 .
Iteration 154 of 5000 .
Iteration 155 of 5000 .
Iteration 156 of 5000 .
Iteration 157 of 5000 .
Iteration 158 of 5000 .
Iteration 159 of 5000 .
Iteration 160 of 5000 .
Iteration 161 of 5000 .
Iteration 162 of 5000 .
Iteration 163 of 5000 .
Iteration 164 of 5000 .
Iteration 165 of 5000 .
Iteration 166 of 5000 .
Iteration 167 of 5000 .
Iteration 168 of 5000 .
Iteration 169 of 5000 .
Iteration 170 of 5000 .
Iteration 171 of 5000 .
Iteration 172 of 5000 .
Iteration 173 of 5000 .
Iteration 174 of 5000 .
Iteration 175 of 5000 .
Iteration 176 of 5000 .
Iteration 177 of 5000 .
Iteration 178 of 5000 .
Iteration 179 of 5000 .
Iteration 180 of 5000 .
Iteration 181 of 5000 .
Iteration 182 of 5000 .
Iteration 183 of 5000 .
Iteration 184 of 5000 .
Iteration 185 of 5000 .
Iteration 186 of 5000 .
Iteration 187 of 5000 .
Iteration 188 of 5000 .
Iteration 189 of 5000 .
Iteration 190 of 5000 .
Iteration 191 of 5000 .
Iteration 192 of 5000 .
Iteration 193 of 5000 .
Iteration 194 of 5000 .
Iteration 195 of 5000 .
Iteration 196 of 5000 .
Iteration 197 of 5000 .
Iteration 198 of 5000 .
Iteration 199 of 5000 .
Iteration 200 of 5000 .
Iteration 201 of 5000 .
Iteration 202 of 5000 .
Iteration 203 of 5000 .
Iteration 204 of 5000 .
Iteration 205 of 5000 .
Iteration 206 of 5000 .
Iteration 207 of 5000 .
Iteration 208 of 5000 .
Iteration 209 of 5000 .
Iteration 210 of 5000 .
Iteration 211 of 5000 .
Iteration 212 of 5000 .
Iteration 213 of 5000 .
Iteration 214 of 5000 .
Iteration 215 of 5000 .
Iteration 216 of 5000 .
Iteration 217 of 5000 .
Iteration 218 of 5000 .
Iteration 219 of 5000 .
Iteration 220 of 5000 .
Iteration 221 of 5000 .
Iteration 222 of 5000 .
Iteration 223 of 5000 .
Iteration 224 of 5000 .
Iteration 225 of 5000 .
Iteration 226 of 5000 .
Iteration 227 of 5000 .
Iteration 228 of 5000 .
Iteration 229 of 5000 .
Iteration 230 of 5000 .
Iteration 231 of 5000 .
Iteration 232 of 5000 .
Iteration 233 of 5000 .
Iteration 234 of 5000 .
Iteration 235 of 5000 .
Iteration 236 of 5000 .
Iteration 237 of 5000 .
Iteration 238 of 5000 .
Iteration 239 of 5000 .
Iteration 240 of 5000 .
Iteration 241 of 5000 .
Iteration 242 of 5000 .
Iteration 243 of 5000 .
Iteration 244 of 5000 .
Iteration 245 of 5000 .
Iteration 246 of 5000 .
Iteration 247 of 5000 .
Iteration 248 of 5000 .
Iteration 249 of 5000 .
Iteration 250 of 5000 .
Iteration 251 of 5000 .
Iteration 252 of 5000 .
Iteration 253 of 5000 .
Iteration 254 of 5000 .
Iteration 255 of 5000 .
Iteration 256 of 5000 .
Iteration 257 of 5000 .
Iteration 258 of 5000 .
Iteration 259 of 5000 .
Iteration 260 of 5000 .
Iteration 261 of 5000 .
Iteration 262 of 5000 .
Iteration 263 of 5000 .
Iteration 264 of 5000 .
Iteration 265 of 5000 .
Iteration 266 of 5000 .
Iteration 267 of 5000 .
Iteration 268 of 5000 .
Iteration 269 of 5000 .
Iteration 270 of 5000 .
Iteration 271 of 5000 .
Iteration 272 of 5000 .
Iteration 273 of 5000 .
Iteration 274 of 5000 .
Iteration 275 of 5000 .
Iteration 276 of 5000 .
Iteration 277 of 5000 .
Iteration 278 of 5000 .
Iteration 279 of 5000 .
Iteration 280 of 5000 .
Iteration 281 of 5000 .
Iteration 282 of 5000 .
Iteration 283 of 5000 .
Iteration 284 of 5000 .
Iteration 285 of 5000 .
Iteration 286 of 5000 .
Iteration 287 of 5000 .
Iteration 288 of 5000 .
Iteration 289 of 5000 .
Iteration 290 of 5000 .
Iteration 291 of 5000 .
Iteration 292 of 5000 .
Iteration 293 of 5000 .
Iteration 294 of 5000 .
Iteration 295 of 5000 .
Iteration 296 of 5000 .
Iteration 297 of 5000 .
Iteration 298 of 5000 .
Iteration 299 of 5000 .
Iteration 300 of 5000 .
Iteration 301 of 5000 .
Iteration 302 of 5000 .
Iteration 303 of 5000 .
Iteration 304 of 5000 .
Iteration 305 of 5000 .
Iteration 306 of 5000 .
Iteration 307 of 5000 .
Iteration 308 of 5000 .
Iteration 309 of 5000 .
Iteration 310 of 5000 .
Iteration 311 of 5000 .
Iteration 312 of 5000 .
Iteration 313 of 5000 .
Iteration 314 of 5000 .
Iteration 315 of 5000 .
Iteration 316 of 5000 .
Iteration 317 of 5000 .
Iteration 318 of 5000 .
Iteration 319 of 5000 .
Iteration 320 of 5000 .
Iteration 321 of 5000 .
Iteration 322 of 5000 .
Iteration 323 of 5000 .
Iteration 324 of 5000 .
Iteration 325 of 5000 .
Iteration 326 of 5000 .
Iteration 327 of 5000 .
Iteration 328 of 5000 .
Iteration 329 of 5000 .
Iteration 330 of 5000 .
Iteration 331 of 5000 .
Iteration 332 of 5000 .
Iteration 333 of 5000 .
Iteration 334 of 5000 .
Iteration 335 of 5000 .
Iteration 336 of 5000 .
Iteration 337 of 5000 .
Iteration 338 of 5000 .
Iteration 339 of 5000 .
Iteration 340 of 5000 .
Iteration 341 of 5000 .
Iteration 342 of 5000 .
Iteration 343 of 5000 .
Iteration 344 of 5000 .
Iteration 345 of 5000 .
Iteration 346 of 5000 .
Iteration 347 of 5000 .
Iteration 348 of 5000 .
Iteration 349 of 5000 .
Iteration 350 of 5000 .
Iteration 351 of 5000 .
Iteration 352 of 5000 .
Iteration 353 of 5000 .
Iteration 354 of 5000 .
Iteration 355 of 5000 .
Iteration 356 of 5000 .
Iteration 357 of 5000 .
Iteration 358 of 5000 .
Iteration 359 of 5000 .
Iteration 360 of 5000 .
Iteration 361 of 5000 .
Iteration 362 of 5000 .
Iteration 363 of 5000 .
Iteration 364 of 5000 .
Iteration 365 of 5000 .
Iteration 366 of 5000 .
Iteration 367 of 5000 .
Iteration 368 of 5000 .
Iteration 369 of 5000 .
Iteration 370 of 5000 .
Iteration 371 of 5000 .
Iteration 372 of 5000 .
Iteration 373 of 5000 .
Iteration 374 of 5000 .
Iteration 375 of 5000 .
Iteration 376 of 5000 .
Iteration 377 of 5000 .
Iteration 378 of 5000 .
Iteration 379 of 5000 .
Iteration 380 of 5000 .
Iteration 381 of 5000 .
Iteration 382 of 5000 .
Iteration 383 of 5000 .
Iteration 384 of 5000 .
Iteration 385 of 5000 .
Iteration 386 of 5000 .
Iteration 387 of 5000 .
Iteration 388 of 5000 .
Iteration 389 of 5000 .
Iteration 390 of 5000 .
Iteration 391 of 5000 .
Iteration 392 of 5000 .
Iteration 393 of 5000 .
Iteration 394 of 5000 .
Iteration 395 of 5000 .
Iteration 396 of 5000 .
Iteration 397 of 5000 .
Iteration 398 of 5000 .
Iteration 399 of 5000 .
Iteration 400 of 5000 .
Iteration 401 of 5000 .
Iteration 402 of 5000 .
Iteration 403 of 5000 .
Iteration 404 of 5000 .
Iteration 405 of 5000 .
Iteration 406 of 5000 .
Iteration 407 of 5000 .
Iteration 408 of 5000 .
Iteration 409 of 5000 .
Iteration 410 of 5000 .
Iteration 411 of 5000 .
Iteration 412 of 5000 .
Iteration 413 of 5000 .
Iteration 414 of 5000 .
Iteration 415 of 5000 .
Iteration 416 of 5000 .
Iteration 417 of 5000 .
Iteration 418 of 5000 .
Iteration 419 of 5000 .
Iteration 420 of 5000 .
Iteration 421 of 5000 .
Iteration 422 of 5000 .
Iteration 423 of 5000 .
Iteration 424 of 5000 .
Iteration 425 of 5000 .
Iteration 426 of 5000 .
Iteration 427 of 5000 .
Iteration 428 of 5000 .
Iteration 429 of 5000 .
Iteration 430 of 5000 .
Iteration 431 of 5000 .
Iteration 432 of 5000 .
Iteration 433 of 5000 .
Iteration 434 of 5000 .
Iteration 435 of 5000 .
Iteration 436 of 5000 .
Iteration 437 of 5000 .
Iteration 438 of 5000 .
Iteration 439 of 5000 .
Iteration 440 of 5000 .
Iteration 441 of 5000 .
Iteration 442 of 5000 .
Iteration 443 of 5000 .
Iteration 444 of 5000 .
Iteration 445 of 5000 .
Iteration 446 of 5000 .
Iteration 447 of 5000 .
Iteration 448 of 5000 .
Iteration 449 of 5000 .
Iteration 450 of 5000 .
Iteration 451 of 5000 .
Iteration 452 of 5000 .
Iteration 453 of 5000 .
Iteration 454 of 5000 .
Iteration 455 of 5000 .
Iteration 456 of 5000 .
Iteration 457 of 5000 .
Iteration 458 of 5000 .
Iteration 459 of 5000 .
Iteration 460 of 5000 .
Iteration 461 of 5000 .
Iteration 462 of 5000 .
Iteration 463 of 5000 .
Iteration 464 of 5000 .
Iteration 465 of 5000 .
Iteration 466 of 5000 .
Iteration 467 of 5000 .
Iteration 468 of 5000 .
Iteration 469 of 5000 .
Iteration 470 of 5000 .
Iteration 471 of 5000 .
Iteration 472 of 5000 .
Iteration 473 of 5000 .
Iteration 474 of 5000 .
Iteration 475 of 5000 .
Iteration 476 of 5000 .
Iteration 477 of 5000 .
Iteration 478 of 5000 .
Iteration 479 of 5000 .
Iteration 480 of 5000 .
Iteration 481 of 5000 .
Iteration 482 of 5000 .
Iteration 483 of 5000 .
Iteration 484 of 5000 .
Iteration 485 of 5000 .
Iteration 486 of 5000 .
Iteration 487 of 5000 .
Iteration 488 of 5000 .
Iteration 489 of 5000 .
Iteration 490 of 5000 .
Iteration 491 of 5000 .
Iteration 492 of 5000 .
Iteration 493 of 5000 .
Iteration 494 of 5000 .
Iteration 495 of 5000 .
Iteration 496 of 5000 .
Iteration 497 of 5000 .
Iteration 498 of 5000 .
Iteration 499 of 5000 .
Iteration 500 of 5000 .
Iteration 501 of 5000 .
Iteration 502 of 5000 .
Iteration 503 of 5000 .
Iteration 504 of 5000 .
Iteration 505 of 5000 .
Iteration 506 of 5000 .
Iteration 507 of 5000 .
Iteration 508 of 5000 .
Iteration 509 of 5000 .
Iteration 510 of 5000 .
Iteration 511 of 5000 .
Iteration 512 of 5000 .
Iteration 513 of 5000 .
Iteration 514 of 5000 .
Iteration 515 of 5000 .
Iteration 516 of 5000 .
Iteration 517 of 5000 .
Iteration 518 of 5000 .
Iteration 519 of 5000 .
Iteration 520 of 5000 .
Iteration 521 of 5000 .
Iteration 522 of 5000 .
Iteration 523 of 5000 .
Iteration 524 of 5000 .
Iteration 525 of 5000 .
Iteration 526 of 5000 .
Iteration 527 of 5000 .
Iteration 528 of 5000 .
Iteration 529 of 5000 .
Iteration 530 of 5000 .
Iteration 531 of 5000 .
Iteration 532 of 5000 .
Iteration 533 of 5000 .
Iteration 534 of 5000 .
Iteration 535 of 5000 .
Iteration 536 of 5000 .
Iteration 537 of 5000 .
Iteration 538 of 5000 .
Iteration 539 of 5000 .
Iteration 540 of 5000 .
Iteration 541 of 5000 .
Iteration 542 of 5000 .
Iteration 543 of 5000 .
Iteration 544 of 5000 .
Iteration 545 of 5000 .
Iteration 546 of 5000 .
Iteration 547 of 5000 .
Iteration 548 of 5000 .
Iteration 549 of 5000 .
Iteration 550 of 5000 .
Iteration 551 of 5000 .
Iteration 552 of 5000 .
Iteration 553 of 5000 .
Iteration 554 of 5000 .
Iteration 555 of 5000 .
Iteration 556 of 5000 .
Iteration 557 of 5000 .
Iteration 558 of 5000 .
Iteration 559 of 5000 .
Iteration 560 of 5000 .
Iteration 561 of 5000 .
Iteration 562 of 5000 .
Iteration 563 of 5000 .
Iteration 564 of 5000 .
Iteration 565 of 5000 .
Iteration 566 of 5000 .
Iteration 567 of 5000 .
Iteration 568 of 5000 .
Iteration 569 of 5000 .
Iteration 570 of 5000 .
Iteration 571 of 5000 .
Iteration 572 of 5000 .
Iteration 573 of 5000 .
Iteration 574 of 5000 .
Iteration 575 of 5000 .
Iteration 576 of 5000 .
Iteration 577 of 5000 .
Iteration 578 of 5000 .
Iteration 579 of 5000 .
Iteration 580 of 5000 .
Iteration 581 of 5000 .
Iteration 582 of 5000 .
Iteration 583 of 5000 .
Iteration 584 of 5000 .
Iteration 585 of 5000 .
Iteration 586 of 5000 .
Iteration 587 of 5000 .
Iteration 588 of 5000 .
Iteration 589 of 5000 .
Iteration 590 of 5000 .
Iteration 591 of 5000 .
Iteration 592 of 5000 .
Iteration 593 of 5000 .
Iteration 594 of 5000 .
Iteration 595 of 5000 .
Iteration 596 of 5000 .
Iteration 597 of 5000 .
Iteration 598 of 5000 .
Iteration 599 of 5000 .
Iteration 600 of 5000 .
Iteration 601 of 5000 .
Iteration 602 of 5000 .
Iteration 603 of 5000 .
Iteration 604 of 5000 .
Iteration 605 of 5000 .
Iteration 606 of 5000 .
Iteration 607 of 5000 .
Iteration 608 of 5000 .
Iteration 609 of 5000 .
Iteration 610 of 5000 .
Iteration 611 of 5000 .
Iteration 612 of 5000 .
Iteration 613 of 5000 .
Iteration 614 of 5000 .
Iteration 615 of 5000 .
Iteration 616 of 5000 .
Iteration 617 of 5000 .
Iteration 618 of 5000 .
Iteration 619 of 5000 .
Iteration 620 of 5000 .
Iteration 621 of 5000 .
Iteration 622 of 5000 .
Iteration 623 of 5000 .
Iteration 624 of 5000 .
Iteration 625 of 5000 .
Iteration 626 of 5000 .
Iteration 627 of 5000 .
Iteration 628 of 5000 .
Iteration 629 of 5000 .
Iteration 630 of 5000 .
Iteration 631 of 5000 .
Iteration 632 of 5000 .
Iteration 633 of 5000 .
Iteration 634 of 5000 .
Iteration 635 of 5000 .
Iteration 636 of 5000 .
Iteration 637 of 5000 .
Iteration 638 of 5000 .
Iteration 639 of 5000 .
Iteration 640 of 5000 .
Iteration 641 of 5000 .
Iteration 642 of 5000 .
Iteration 643 of 5000 .
Iteration 644 of 5000 .
Iteration 645 of 5000 .
Iteration 646 of 5000 .
Iteration 647 of 5000 .
Iteration 648 of 5000 .
Iteration 649 of 5000 .
Iteration 650 of 5000 .
Iteration 651 of 5000 .
Iteration 652 of 5000 .
Iteration 653 of 5000 .
Iteration 654 of 5000 .
Iteration 655 of 5000 .
Iteration 656 of 5000 .
Iteration 657 of 5000 .
Iteration 658 of 5000 .
Iteration 659 of 5000 .
Iteration 660 of 5000 .
Iteration 661 of 5000 .
Iteration 662 of 5000 .
Iteration 663 of 5000 .
Iteration 664 of 5000 .
Iteration 665 of 5000 .
Iteration 666 of 5000 .
Iteration 667 of 5000 .
Iteration 668 of 5000 .
Iteration 669 of 5000 .
Iteration 670 of 5000 .
Iteration 671 of 5000 .
Iteration 672 of 5000 .
Iteration 673 of 5000 .
Iteration 674 of 5000 .
Iteration 675 of 5000 .
Iteration 676 of 5000 .
Iteration 677 of 5000 .
Iteration 678 of 5000 .
Iteration 679 of 5000 .
Iteration 680 of 5000 .
Iteration 681 of 5000 .
Iteration 682 of 5000 .
Iteration 683 of 5000 .
Iteration 684 of 5000 .
Iteration 685 of 5000 .
Iteration 686 of 5000 .
Iteration 687 of 5000 .
Iteration 688 of 5000 .
Iteration 689 of 5000 .
Iteration 690 of 5000 .
Iteration 691 of 5000 .
Iteration 692 of 5000 .
Iteration 693 of 5000 .
Iteration 694 of 5000 .
Iteration 695 of 5000 .
Iteration 696 of 5000 .
Iteration 697 of 5000 .
Iteration 698 of 5000 .
Iteration 699 of 5000 .
Iteration 700 of 5000 .
Iteration 701 of 5000 .
Iteration 702 of 5000 .
Iteration 703 of 5000 .
Iteration 704 of 5000 .
Iteration 705 of 5000 .
Iteration 706 of 5000 .
Iteration 707 of 5000 .
Iteration 708 of 5000 .
Iteration 709 of 5000 .
Iteration 710 of 5000 .
Iteration 711 of 5000 .
Iteration 712 of 5000 .
Iteration 713 of 5000 .
Iteration 714 of 5000 .
Iteration 715 of 5000 .
Iteration 716 of 5000 .
Iteration 717 of 5000 .
Iteration 718 of 5000 .
Iteration 719 of 5000 .
Iteration 720 of 5000 .
Iteration 721 of 5000 .
Iteration 722 of 5000 .
Iteration 723 of 5000 .
Iteration 724 of 5000 .
Iteration 725 of 5000 .
Iteration 726 of 5000 .
Iteration 727 of 5000 .
Iteration 728 of 5000 .
Iteration 729 of 5000 .
Iteration 730 of 5000 .
Iteration 731 of 5000 .
Iteration 732 of 5000 .
Iteration 733 of 5000 .
Iteration 734 of 5000 .
Iteration 735 of 5000 .
Iteration 736 of 5000 .
Iteration 737 of 5000 .
Iteration 738 of 5000 .
Iteration 739 of 5000 .
Iteration 740 of 5000 .
Iteration 741 of 5000 .
Iteration 742 of 5000 .
Iteration 743 of 5000 .
Iteration 744 of 5000 .
Iteration 745 of 5000 .
Iteration 746 of 5000 .
Iteration 747 of 5000 .
Iteration 748 of 5000 .
Iteration 749 of 5000 .
Iteration 750 of 5000 .
Iteration 751 of 5000 .
Iteration 752 of 5000 .
Iteration 753 of 5000 .
Iteration 754 of 5000 .
Iteration 755 of 5000 .
Iteration 756 of 5000 .
Iteration 757 of 5000 .
Iteration 758 of 5000 .
Iteration 759 of 5000 .
Iteration 760 of 5000 .
Iteration 761 of 5000 .
Iteration 762 of 5000 .
Iteration 763 of 5000 .
Iteration 764 of 5000 .
Iteration 765 of 5000 .
Iteration 766 of 5000 .
Iteration 767 of 5000 .
Iteration 768 of 5000 .
Iteration 769 of 5000 .
Iteration 770 of 5000 .
Iteration 771 of 5000 .
Iteration 772 of 5000 .
Iteration 773 of 5000 .
Iteration 774 of 5000 .
Iteration 775 of 5000 .
Iteration 776 of 5000 .
Iteration 777 of 5000 .
Iteration 778 of 5000 .
Iteration 779 of 5000 .
Iteration 780 of 5000 .
Iteration 781 of 5000 .
Iteration 782 of 5000 .
Iteration 783 of 5000 .
Iteration 784 of 5000 .
Iteration 785 of 5000 .
Iteration 786 of 5000 .
Iteration 787 of 5000 .
Iteration 788 of 5000 .
Iteration 789 of 5000 .
Iteration 790 of 5000 .
Iteration 791 of 5000 .
Iteration 792 of 5000 .
Iteration 793 of 5000 .
Iteration 794 of 5000 .
Iteration 795 of 5000 .
Iteration 796 of 5000 .
Iteration 797 of 5000 .
Iteration 798 of 5000 .
Iteration 799 of 5000 .
Iteration 800 of 5000 .
Iteration 801 of 5000 .
Iteration 802 of 5000 .
Iteration 803 of 5000 .
Iteration 804 of 5000 .
Iteration 805 of 5000 .
Iteration 806 of 5000 .
Iteration 807 of 5000 .
Iteration 808 of 5000 .
Iteration 809 of 5000 .
Iteration 810 of 5000 .
Iteration 811 of 5000 .
Iteration 812 of 5000 .
Iteration 813 of 5000 .
Iteration 814 of 5000 .
Iteration 815 of 5000 .
Iteration 816 of 5000 .
Iteration 817 of 5000 .
Iteration 818 of 5000 .
Iteration 819 of 5000 .
Iteration 820 of 5000 .
Iteration 821 of 5000 .
Iteration 822 of 5000 .
Iteration 823 of 5000 .
Iteration 824 of 5000 .
Iteration 825 of 5000 .
Iteration 826 of 5000 .
Iteration 827 of 5000 .
Iteration 828 of 5000 .
Iteration 829 of 5000 .
Iteration 830 of 5000 .
Iteration 831 of 5000 .
Iteration 832 of 5000 .
Iteration 833 of 5000 .
Iteration 834 of 5000 .
Iteration 835 of 5000 .
Iteration 836 of 5000 .
Iteration 837 of 5000 .
Iteration 838 of 5000 .
Iteration 839 of 5000 .
Iteration 840 of 5000 .
Iteration 841 of 5000 .
Iteration 842 of 5000 .
Iteration 843 of 5000 .

In [ ]:
wins

           Country  Wins
0            Spain  4992
1           Brazil  4974
2           France  4961
3          Germany  4935
4            Italy  4598
5        Argentina  4691
6         Portugal  4468
7          Belgium  4606
8          England  4174
9      Netherlands  4051
10         Uruguay  4003
11         Croatia  3586
12        Colombia  3159
13     Switzerland  2786
14         Denmark  2614
15          Mexico  2207
16         Senegal  2081
17   Cote d'Ivoire  2024
18          Turkey  1471
19          Poland  2373
20           Chile  1849
21         Morocco  1646
22         Algeria  1204
23         Nigeria   760
24           Japan   613
25             USA   539
26  Korea Republic   275
27       Australia   225
28        China PR    60
29    Saudi Arabia    33
30          Canada    42
31           Qatar     0

In [ ]:
whole_wins

           Country  Wins
0            Spain  1300
1           Brazil  1233
2           France  1029
3          Germany   810
4            Italy   146
5        Argentina   161
6         Portugal   113
7          Belgium   140
8          England    34
9      Netherlands    27
10         Uruguay     5
11         Croatia     2
12        Colombia     0
13     Switzerland     0
14         Denmark     0
15          Mexico     0
16         Senegal     0
17   Cote d'Ivoire     0
18          Turkey     0
19          Poland     0
20           Chile     0
21         Morocco     0
22         Algeria     0
23         Nigeria     0
24           Japan     0
25             USA     0
26  Korea Republic     0
27       Australia     0
28        China PR     0
29    Saudi Arabia     0
30          Canada     0
31           Qatar     0

In [ ]:
wins["Wins"]= wins["Wins"] / N * 100

In [ ]:
whole_wins["Wins"]= whole_wins["Wins"] / N * 100

In [ ]:
whole_wins

           Country   Wins
0            Spain  25.10
1           Brazil  24.48
2           France  21.76
3          Germany  16.04
4            Italy   2.92
5        Argentina   3.44
6         Portugal   2.20
7          Belgium   2.88
8          England   0.54
9      Netherlands   0.40
10         Uruguay   0.20
11         Croatia   0.04
12        Colombia   0.00
13     Switzerland   0.00
14         Denmark   0.00
15          Mexico   0.00
16         Senegal   0.00
17   Cote d'Ivoire   0.00
18          Turkey   0.00
19          Poland   0.00
20           Chile   0.00
21         Morocco   0.00
22         Algeria   0.00
23         Nigeria   0.00
24           Japan   0.00
25             USA   0.00
26  Korea Republic   0.00
27       Australia   0.00
28        China PR   0.00
29    Saudi Arabia   0.00
30          Canada   0.00
31           Qatar   0.00

In [ ]:
wins

           Country   Wins
0            Spain  99.74
1           Brazil  99.46
2           France  99.16
3          Germany  98.38
4            Italy  92.06
5        Argentina  93.56
6         Portugal  89.12
7          Belgium  91.84
8          England  83.02
9      Netherlands  81.24
10         Uruguay  79.00
11         Croatia  71.00
12        Colombia  62.98
13     Switzerland  55.64
14         Denmark  52.86
15          Mexico  45.90
16         Senegal  42.10
17   Cote d'Ivoire  40.30
18          Turkey  31.56
19          Poland  47.50
20           Chile  35.82
21         Morocco  33.32
22         Algeria  23.32
23         Nigeria  14.82
24           Japan  12.32
25             USA  10.92
26  Korea Republic   6.06
27       Australia   4.40
28        China PR   1.22
29    Saudi Arabia   0.52
30          Canada   0.86
31           Qatar   0.00

In [ ]:
wins = wins.sort_values(by="Wins",ascending=False)

In [ ]:
whole_wins = whole_wins.sort_values(by="Wins",ascending=False)

In [ ]:
wins.to_csv('group_stage.csv',index=False)

In [ ]:
whole_wins.to_csv('WC_champions.csv',index=False)